image: docker:20

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

Build:
  stage: build
  tags:
    - docker
  script:
    - >
      docker build
      --pull
      --tag $CI_REGISTRY_IMAGE:latest
      .
    - docker push $CI_REGISTRY_IMAGE:latest
    - export PHP_VERSION="v`docker run --rm $CI_REGISTRY_IMAGE:latest -v | grep -Eo '8\.[0-9]\.[0-9]?[0-9]' | head -n 1`"
    - echo $PHP_VERSION
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$PHP_VERSION
    - docker push $CI_REGISTRY_IMAGE:$PHP_VERSION