image: docker:20

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

build:version:
  stage: build
  image: php:8-alpine
  script:
   - php latest.php > latest.txt
build:docker:
  stage: build
  needs: ["build:version"]
  tags:
    - docker
  script:
    - VERSION=$(cat latest.txt)
    - >
      docker build
      --pull
      --build-arg="PHP_VERSION=$VERSION"
      --tag $CI_REGISTRY_IMAGE:latest
      .
    - docker push $CI_REGISTRY_IMAGE:latest
    - export PHP_VERSION="`docker run --entrypoint=/usr/local/bin/php --rm $CI_REGISTRY_IMAGE:latest -v | grep -Eo '8\.[0-9]\.[0-9]?[0-9]' | head -n 1`"
    - echo $PHP_VERSION
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$PHP_VERSION
    - docker push $CI_REGISTRY_IMAGE:$PHP_VERSION