#!/bin/sh

bin/console cache:warmup
bin/console doctrine:schema:validate

if [ "$APP_ENV" == "dev" ]
then
  echo "Disabling opcache"
  echo "" >> /usr/local/etc/php/conf.d/php-common.ini
  echo "opcache.enable=0" >> /usr/local/etc/php/conf.d/php-common.ini

  echo "Resetting permissions"
  chown -Rf 82:82 /var/www

  echo "Downloading latest composer"

  php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  php composer-setup.php 
  php -r "unlink('composer-setup.php');"

  set -x

  php composer.phar install -v --ignore-platform-reqs

  php bin/console doctrine:database:create --if-not-exists
  php bin/console doctrine:schema:update --force

fi

echo "Setting www.conf from ENV";
echo "; Medleybox config" >> /usr/local/etc/php-fpm.d/www.conf

echo "Setting workers count '$FPM_WORKERS'"
echo "pm = static" >> /usr/local/etc/php-fpm.d/www.conf
echo "pm.max_children = $FPM_WORKERS" >> /usr/local/etc/php-fpm.d/www.conf

echo "Setting worker memory limit to '$FPM_MEMORY_LIMIT'"
echo "php_admin_value[memory_limit] = $FPM_MEMORY_LIMIT" >> /usr/local/etc/php-fpm.d/www.conf

echo ""

cat /usr/local/etc/php-fpm.d/www.conf

exec /var/www/bin/docker-entrypoint

exec docker-php-entrypoint php-fpm
